version: '3.8'

services:

  kronxy.api:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: 5000
      ConnectionStrings__Database: Host=kronxy-db;Port=5432;Database=${KRONXY_DB_NAME:-kronxy};Username=${KRONXY_DB_USER:-kronxy_app};Password=${KRONXY_DB_PASSWORD}
    ports:
      - "127.0.0.1:5000:5000"
